package com.Servlet;


import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletResponse;

@SuppressWarnings("serial")
@WebServlet("/HttpServletRequest")
public class HttpServletRequest extends HttpServlet {

    @Override
    protected void doGet(javax.servlet.http.HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException 
    {
        // Set response content type
        response.setContentType("text/html");

        try (PrintWriter out = response.getWriter()) 
        {
            out.println("<html>");
            out.println("<head><title>GET Request</title></head>");
            out.println("<body>");
            out.println("<h1>Handling GET Request</h1>");
            out.println("<p>This response is generated by handling a GET request.</p>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    @Override
    protected void doPost(javax.servlet.http.HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException 
    {
        // Set response content type
        response.setContentType("text/html");

        // Retrieve parameters from POST request
        String name = request.getParameter("name");
        String email = request.getParameter("email");

        try (PrintWriter out = response.getWriter()) 
        {
            out.println("<html>");
            out.println("<head><title>POST Request</title></head>");
            out.println("<body>");
            out.println("<h1>Handling POST Request</h1>");
            if (name != null && email != null) {
                out.println("<p><strong>Name:</strong> " + name + "</p>");
                out.println("<p><strong>Email:</strong> " + email + "</p>");
            } else {
                out.println("<p>Error: Missing name or email!</p>");
            }
            out.println("</body>");
            out.println("</html>");
        }
    }
}
